from flask_restful import Api, Resource
from sqlalchemy import Text, JSON
from __init__ import app, db
from sqlalchemy import Column, Integer, String, Float
from sqlite3 import IntegrityError
from model.librarydb import Book 
from model.user import User

# Database model for the cart
class CartItem(db.Model):
    __tablename__ = 'cart_items'
    id = Column(db.Integer, primary_key=True)
    title = Column(String, db.ForeignKey(Book.title), nullable=False)
    price = Column(db.Float, nullable=False)
    quantity = Column(db.Integer, nullable=False)
    username = Column(String, db.ForeignKey(User._name), nullable=False)

    def create(self):
        try:
            db.session.add(self)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            raise e
        
    def read(self):
        return {
            'id': self.id,
            'title' : self.title,
            'price': self.price,
            'quantity': self.quantity,
            'username': self.username
        }
        
@staticmethod
def restore(data):
    restored_cart_items = {}

    for cart_item_data in data:
        # Remove 'id' if it's present in the input data, as it's auto-generated by the database
        cart_item_data.pop('id', None)

        # Check if the cart item already exists (based on title and username)
        existing_cart_item = CartItem.query.filter_by(
            title=cart_item_data.get('title'),
            username=cart_item_data.get('username')
        ).first()

        if existing_cart_item:
            # Update the existing cart item with new data
            for key, value in cart_item_data.items():
                setattr(existing_cart_item, key, value)

            try:
                db.session.commit()
                restored_cart_items[existing_cart_item.id] = {
                    'status': 'updated',
                    'cart_item': existing_cart_item.read()
                }
            except Exception as e:
                db.session.rollback()
                restored_cart_items[existing_cart_item.id] = {
                    'status': 'error',
                    'message': str(e)
                }
        else:
            # Create a new cart item
            try:
                new_cart_item = CartItem(**cart_item_data)
                db.session.add(new_cart_item)
                db.session.commit()
                restored_cart_items[new_cart_item.id] = {
                    'status': 'created',
                    'cart_item': new_cart_item.read()
                }
            except Exception as e:
                db.session.rollback()
                restored_cart_items[f'new_{len(restored_cart_items)+1}'] = {
                    'status': 'error',
                    'message': str(e)
                }

    return restored_cart_items

# Initialize cart items
def init_books_in_cart():
    books_in_cart = [
        {"id": 1, "title": "1984", "price": 15.00, "quantity": 2, "_name": "Avika"},
        {"id": 2, "title": "The Hobbit", "price": 12.00, "quantity": 1, "_name": "Soumini"},
        {"id": 3, "title": "The Outsiders", "price": 10.00, "quantity": 4, "_name": "Aarush"},
        {"id": 4, "title": "A Game of Thrones", "price": 13.00, "quantity": 1, "_name": "Aditi"},
        {"id": 5, "title": "The Nightingale", "price": 16.00, "quantity": 2, "_name": "Thomas Edison"}
    ]

    for book in books_in_cart:
        # Check for duplicate entries to avoid IntegrityError
        existing_cart_item = CartItem.query.filter_by(title=book["title"], username=book["_name"]).first()
        if not existing_cart_item:
            new_cart_item = CartItem(
                title=book["title"],
                price=book["price"],
                quantity=book["quantity"],
                username=book["_name"]
            )
            db.session.add(new_cart_item)  # Add valid CartItem instances

    try:
        db.session.commit()  # Commit changes to the database
    except IntegrityError as e:
        db.session.rollback()
        print(f"IntegrityError: {e}")
    except Exception as e:
        db.session.rollback()
        print(f"Unexpected error: {e}")

# Initialize the database
with app.app_context():
    db.create_all()  # Create tables
    init_books_in_cart()
